[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BIG-DATA-MORT"
version = "0.1.0"
description = "UE Big Data - BIG-DATA-MORT project"
dependencies = ["pyspark", "altair", "requests"]

[tool.setuptools]
py-modules = ["lab3"]
